/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programacion_orientada_a_objetos;

/**
 *
 * @author jcaba
 */
public class VentanaAviones extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAviones
     */
    public VentanaAviones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboAviones = new javax.swing.JComboBox<>();
        btnInfo = new javax.swing.JButton();
        btnDespegar = new javax.swing.JButton();
        btnAterrizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboAviones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnInfo.setText("jButton1");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnDespegar.setText("jButton2");
        btnDespegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespegarActionPerformed(evt);
            }
        });

        btnAterrizar.setText("jButton3");
        btnAterrizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAterrizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout areaTextoLayout = new javax.swing.GroupLayout(areaTexto);
        areaTexto.setLayout(areaTextoLayout);
        areaTextoLayout.setHorizontalGroup(
            areaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        areaTextoLayout.setVerticalGroup(
            areaTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(areaTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDespegar)
                        .addGap(162, 162, 162)))
                .addComponent(btnAterrizar)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(comboAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(comboAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfo)
                    .addComponent(btnDespegar)
                    .addComponent(btnAterrizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Avionturistico turistico1 = new Avionturistico("Boeing 737", 180);
        Avionturistico turistico2 = new Avionturistico("Airbus A320", 150);
        Avionmilitar militar1 = new Avionmilitar("Caza", "Misiles aire-aire");
        Avionmilitar militar2 = new Avionmilitar("Transporte", "Tropas y equipo");
        Avionprivado privado1 = new Avionprivado("Empresa XYZ", "Nueva York");
        Avionprivado privado2 = new Avionprivado("Familia Pérez", "París");
        aviones = new Avion_3[]{turistico1, turistico2, militar1, militar2, privado1, privado2};

    
    comboAviones.addItem("Avión Turístico 1");
        comboAviones.addItem("Avión Turístico 2");
        comboAviones.addItem("Avión Militar 1");
        comboAviones.addItem("Avión Militar 2");
        comboAviones.addItem("Avión Privado 1");
        comboAviones.addItem("Avión Privado 2");
    
    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
         areaTexto.append("=== Información ===\n");
        aviones[comboAviones.getSelectedIndex()].informacion();
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnDespegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespegarActionPerformed
        // TODO add your handling code here:
         areaTexto.append("=== Despegue ===\n");
        aviones[comboAviones.getSelectedIndex()].despegar()
    }//GEN-LAST:event_btnDespegarActionPerformed

    private void btnAterrizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAterrizarActionPerformed
        // TODO add your handling code here:
        areaTexto.append("=== Aterrizaje ===\n");
        aviones[comboAviones.getSelectedIndex()].aterrizar();
    }//GEN-LAST:event_btnAterrizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAviones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaTexto;
    private javax.swing.JButton btnAterrizar;
    private javax.swing.JButton btnDespegar;
    private javax.swing.JButton btnInfo;
    private javax.swing.JComboBox<String> comboAviones;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
